### ISSUE TITLE
The Clear message spams 20 message in ones

### ISSUE THREAD

**Issue by DragonfireHD** [HazardTeam/AutoClearChunk#1]
If the plugin clear the chunks he spams the message 20 in ones in the chat please fix

**Comment by DragonfireHD** [comment]
![Screenshot_20210920-200649_Minecraft](https://user-images.githubusercontent.com/50929188/134070796-20ed9ebc-4a29-437d-9bdb-d493be6ebd4c.png)

**Comment by MulqiGaming64** [comment]
yes, alredy fixed

**Comment by ItsRealNise** [comment]
Already fixed
