### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GamerMJay** [HazardTeam/AutoClearChunk#5]
[20:40:15.234] [Server thread/INFO]: Enabling AutoClearChunk v2.2.0

Fatal error: Declaration of HazardTeam\AutoClearChunk\libs\JackMD\UpdateNotifier\task\UpdateNotifyTask::onCompletion(pocketmine\Server $server): void must be compatible with pocketmine\scheduler\AsyncTask::onCompletion(): void in phar:///home/minecraft/plugins/AutoClearChunk (1).phar/src/HazardTeam/AutoClearChunk/libs/JackMD/UpdateNotifier/task/UpdateNotifyTask.php on line 83

**Comment by AIPTU** [comment]
Fixed https://github.com/HazardTeam/AutoClearChunk/commit/bbd1cb07b87320e5fb381f90e43141f89282efc8
