### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by TrinitroToluen0** [HazardTeam/AutoClearChunk#67]
Add an option to disable the message, or an option to show the message only to people with specific permissions.

I think it is not necessary to show that "Chunks cleared" message to all the players

**Comment by TrinitroToluen0** [comment]
Btw i tried to leave the message blank in the config file but it says that it must be a non empty string

**Comment by XanderID** [comment]
Solved in New Version, thx for Making Suggestions!
